from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Iterable

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.version import PRODUCT_NAME
from core.paths import ensure_directories
from core.units import format_value
from knowledge.service import get_knowledge_base
from vehicle.models import DiagnosticSession, VehicleProfile


class PDFReportGenerator:
    def __init__(self) -> None:
        self.paths = ensure_directories()

    def generate(self, session: DiagnosticSession, vehicle: VehicleProfile | None, output_path: Path | None = None, units: str = "metric", include_vin: bool = True) -> Path:
        if output_path is None:
            stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
            output_path = self.paths.reports / f"AutoMindAI-Report-{stamp}.pdf"
        output_path.parent.mkdir(parents=True, exist_ok=True)

        styles = getSampleStyleSheet()
        title = ParagraphStyle(
            "AutoMindTitle", parent=styles["Title"], textColor=colors.HexColor("#0F172A"),
            fontName="Helvetica-Bold", fontSize=22, leading=26, spaceAfter=8
        )
        section = ParagraphStyle(
            "AutoMindSection", parent=styles["Heading2"], textColor=colors.HexColor("#0F766E"),
            fontName="Helvetica-Bold", fontSize=13, leading=16, spaceBefore=10, spaceAfter=6
        )
        body = ParagraphStyle(
            "AutoMindBody", parent=styles["BodyText"], textColor=colors.HexColor("#1F2937"),
            fontName="Helvetica", fontSize=9.4, leading=13, alignment=TA_LEFT
        )
        small = ParagraphStyle("AutoMindSmall", parent=body, fontSize=8, leading=10, textColor=colors.HexColor("#64748B"))

        doc = SimpleDocTemplate(
            str(output_path), pagesize=A4, leftMargin=18*mm, rightMargin=18*mm,
            topMargin=18*mm, bottomMargin=18*mm, title=f"AutoMind AI Diagnostic Report {session.id}"
        )
        story = [
            Paragraph("AutoMind AI", title),
            Paragraph("Automotive Diagnostic Health Report", styles["Heading3"]),
            Paragraph(f"Generated by {PRODUCT_NAME}", small),
            Spacer(1, 8),
        ]

        if session.connection_mode == "simulation":
            story.append(_banner("SIMULATION MODE - This report contains simulated data and is not a real vehicle diagnosis."))
            story.append(Spacer(1, 8))

        story += [Paragraph("Vehicle Information", section)]
        vehicle_rows = [
            ["Vehicle", vehicle.display_name if vehicle else "Unknown"],
            ["VIN", (vehicle.vin if vehicle and vehicle.vin else "Unavailable") if include_vin else "Hidden by privacy setting"],
            ["Engine", vehicle.engine if vehicle and vehicle.engine else "Unavailable"],
            ["Fuel Type", vehicle.fuel_type if vehicle else "Unavailable"],
            ["Diagnostic Date", session.started_at],
            ["Adapter / Mode", session.adapter or session.connection_mode],
            ["Health Summary", session.health_status],
        ]
        story.append(_key_value_table(vehicle_rows))

        story.append(Paragraph("Detected Faults", section))
        if not session.dtcs:
            story.append(Paragraph("No stored OBD-II DTCs were detected in this session.", body))
        else:
            rows = [["Code", "Status", "Description", "Severity"]]
            for dtc in session.dtcs:
                rows.append([dtc.code, dtc.status, Paragraph(_escape(dtc.description), body), dtc.severity])
            table = Table(rows, colWidths=[22*mm, 25*mm, 92*mm, 24*mm], repeatRows=1)
            table.setStyle(TableStyle([
                ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0F172A")),
                ("TEXTCOLOR", (0,0), (-1,0), colors.white),
                ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
                ("FONTSIZE", (0,0), (-1,-1), 8),
                ("VALIGN", (0,0), (-1,-1), "TOP"),
                ("GRID", (0,0), (-1,-1), 0.3, colors.HexColor("#CBD5E1")),
                ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.HexColor("#F8FAFC")]),
                ("LEFTPADDING", (0,0), (-1,-1), 5), ("RIGHTPADDING", (0,0), (-1,-1), 5),
                ("TOPPADDING", (0,0), (-1,-1), 5), ("BOTTOMPADDING", (0,0), (-1,-1), 5),
            ]))
            story.append(table)

        story.append(Paragraph("Live Data Summary", section))
        live_rows = [["PID", "Measurement", "Value"]]
        for pid, item in session.live_data.items():
            if not item.supported:
                display = "Not Supported"
            elif item.value is None:
                display = "Unavailable"
            else:
                text, target_unit = format_value(item.value, item.unit, units)
                display = f"{text} {target_unit}".strip()
            live_rows.append([pid, item.name, display])
        live_table = Table(live_rows[:16], colWidths=[23*mm, 85*mm, 55*mm], repeatRows=1)
        live_table.setStyle(_table_style())
        story.append(live_table)

        if session.freeze_frame:
            story.append(Paragraph("Freeze Frame", section))
            ff_rows = [["PID / Item", "Value"]] + _freeze_frame_rows(session.freeze_frame, units)
            t = Table(ff_rows, colWidths=[55*mm, 108*mm], repeatRows=1)
            t.setStyle(_table_style())
            story.append(t)

        story.append(Paragraph("Diagnostic Interpretation", section))
        for finding in session.findings:
            story.append(Paragraph(_escape(finding.title), styles["Heading4"]))
            story.append(Paragraph("<b>Observed evidence</b>", body))
            story.extend(_bullets(finding.evidence, body))
            if finding.possible_causes:
                story.append(Paragraph("<b>Possible causes (not confirmed)</b>", body))
                for cause in finding.possible_causes[:8]:
                    text = f"{cause.get('cause','')} - {cause.get('reason','')}"
                    story.extend(_bullets([text], body))
            story.append(Paragraph("<b>Recommended checks</b>", body))
            story.extend(_numbered(finding.recommended_steps, body))
            story.append(Paragraph(f"<b>Confidence / uncertainty:</b> {_escape(finding.confidence)}", body))
            for warning in finding.warnings:
                story.append(Paragraph(f"<b>Warning:</b> {_escape(warning)}", body))
            story.append(Spacer(1, 6))

        if session.ai_analysis:
            story.append(PageBreak())
            story.append(Paragraph("AI Analysis", section))
            ai = session.ai_analysis
            story.append(Paragraph(_escape(ai.summary), body))
            story.append(Paragraph("<b>Observed Evidence</b>", body)); story.extend(_bullets(ai.observed_evidence, body))
            story.append(Paragraph("<b>Possible Causes</b>", body)); story.extend(_bullets(ai.possible_causes, body))
            story.append(Paragraph("<b>Recommended Diagnostic Steps</b>", body)); story.extend(_numbered(ai.recommended_steps, body))
            story.append(Paragraph("<b>Additional Measurements</b>", body)); story.extend(_bullets(ai.additional_measurements, body))
            story.append(Paragraph(f"<b>Confidence / Uncertainty:</b> {_escape(ai.confidence)}", body))
            story.extend([Paragraph(f"<b>Warning:</b> {_escape(w)}", body) for w in ai.warnings])

        story.append(Paragraph("Technician / User Notes", section))
        story.append(Paragraph(_escape(session.user_notes or "No notes were entered."), body))
        story.append(Paragraph("Important Disclaimer", section))
        story.append(Paragraph(
            "AutoMind AI is a diagnostic assistant. OBD-II codes and measured sensor values are evidence from the ECU or simulator; suggested mechanical causes are hypotheses that require appropriate inspection and testing. This report does not replace vehicle-specific service information, qualified diagnosis, or safe workshop procedures. Do not rely on this report for safety-critical repair decisions without verification.",
            small,
        ))

        doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
        return output_path


def _escape(text: str) -> str:
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _banner(text: str) -> Table:
    t = Table([[text]], colWidths=[163*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,-1), colors.HexColor("#FEF3C7")),
        ("TEXTCOLOR", (0,0), (-1,-1), colors.HexColor("#92400E")),
        ("FONTNAME", (0,0), (-1,-1), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 8.5),
        ("BOX", (0,0), (-1,-1), 0.5, colors.HexColor("#F59E0B")),
        ("LEFTPADDING", (0,0), (-1,-1), 8), ("RIGHTPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING", (0,0), (-1,-1), 7), ("BOTTOMPADDING", (0,0), (-1,-1), 7),
    ]))
    return t


def _key_value_table(rows: list[list[str]]) -> Table:
    t = Table(rows, colWidths=[45*mm, 118*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#F1F5F9")),
        ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 8.5),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("GRID", (0,0), (-1,-1), 0.3, colors.HexColor("#CBD5E1")),
        ("LEFTPADDING", (0,0), (-1,-1), 6), ("RIGHTPADDING", (0,0), (-1,-1), 6),
        ("TOPPADDING", (0,0), (-1,-1), 5), ("BOTTOMPADDING", (0,0), (-1,-1), 5),
    ]))
    return t


def _table_style() -> TableStyle:
    return TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 8),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("GRID", (0,0), (-1,-1), 0.3, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("LEFTPADDING", (0,0), (-1,-1), 5), ("RIGHTPADDING", (0,0), (-1,-1), 5),
        ("TOPPADDING", (0,0), (-1,-1), 4), ("BOTTOMPADDING", (0,0), (-1,-1), 4),
    ])


def _bullets(items: Iterable[str], style: ParagraphStyle) -> list[Paragraph]:
    return [Paragraph(f"&bull; {_escape(item)}", style) for item in items]


def _numbered(items: Iterable[str], style: ParagraphStyle) -> list[Paragraph]:
    return [Paragraph(f"{i}. {_escape(item)}", style) for i, item in enumerate(items, 1)]


def _freeze_frame_rows(freeze_frame: dict[str, object], units: str) -> list[list[str]]:
    kb = get_knowledge_base()
    rows: list[list[str]] = []
    for key, raw in freeze_frame.items():
        pid = str(key).upper()
        info = kb.pid_info(pid)
        label = f"{pid} - {info.get('name', '')}".rstrip(" -")
        if isinstance(raw, dict):
            name = str(raw.get("name") or info.get("name") or "").strip()
            if name:
                label = f"{pid} - {name}"
            value = raw.get("value")
            unit = str(raw.get("unit") or info.get("unit") or "")
        else:
            value = raw
            unit = str(info.get("unit") or "")
        if isinstance(value, (int, float)):
            text, target_unit = format_value(value, unit, units)
            display = f"{text} {target_unit}".strip()
        elif value is None:
            display = "Unavailable"
        else:
            display = str(value)
        rows.append([label, display])
    return rows


def _footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#64748B"))
    canvas.drawString(18*mm, 9*mm, "AutoMind AI - Diagnostic Assistant")
    canvas.drawRightString(192*mm, 9*mm, f"Page {doc.page}")
    canvas.restoreState()
